---
title: "PNC subject info"
author: "Chenying Zhao"
output: html_document
---

This Rmd is to calculate the subject statistics in the PNC dataset used in ModelArray paper.

```{r load libraries, include=FALSE}
rm(list=ls())
library(testthat)
library(dplyr)
```

```{r inputs}
num.subj <- 938
fn.csv <- paste0("../../data/data_from_josiane/df_example_n", toString(num.subj), ".csv")

phenotypes <- read.csv(fn.csv)
# check # subjects matches:
if (nrow(phenotypes) != num.subj) {
  stop(paste0("number of subjects in .csv = ", toString(nrow(phenotypes)), ", is not equal to entered number = ", toString(num.subj)))
}

print(paste0("total number of subjects = ", toString(num.subj)))
```

```{r age, echo=FALSE}
expect_false(is.na(phenotypes$Age) %>% any())   # there should not be any NAs, i.e. all should be FALSE, without any TRUE
expect_false(anyNA(phenotypes$Age))   # there should not be any NAs

age.min <- min(phenotypes$Age)
age.max <- max(phenotypes$Age)
age.mean <- mean(phenotypes$Age)
age.sd <- sd(phenotypes$Age)

str.digits <- "%.3f"
print("the following digits is: ")
print(str.digits)

print(paste0("min of age = ", sprintf(str.digits, age.min), " years"))
print(paste0("max of age = ", sprintf(str.digits, age.max), " years"))
print(paste0("mean of age = ", sprintf(str.digits, age.mean), " years"))
print(paste0("sd of age = ", sprintf(str.digits, age.sd), " years"))
```

```{r sex, echo=FALSE}
expect_false(is.na(phenotypes$sex) %>% any())   # there should not be any NAs, i.e. all should be FALSE, without any TRUE
expect_false(anyNA(phenotypes$sex))   # there should not be any NAs

# sex=1 male and 2 female <- slack 2021.8.23
num.M <- length(phenotypes$sex[phenotypes$sex == 1])
num.F <- length(phenotypes$sex[phenotypes$sex == 2])
expect_equal(num.M + num.F,
             num.subj)

print(paste0("number of males = ", sprintf("%d", num.M)))
print(paste0("number of females = ", sprintf("%d", num.F)))
```